package com.alpirres.Modelo;
// Generated 03-dic-2019 8:56:38 by Hibernate Tools 4.3.1



/**
 * CircuEjercicio generated by hbm2java
 */
public class CircuEjercicio  implements java.io.Serializable {


     private Integer id;
     private Circuito circuito;
     private Ejercicio ejercicio;

    public CircuEjercicio() {
    }

    public CircuEjercicio(Circuito circuito, Ejercicio ejercicio) {
       this.circuito = circuito;
       this.ejercicio = ejercicio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Circuito getCircuito() {
        return this.circuito;
    }
    
    public void setCircuito(Circuito circuito) {
        this.circuito = circuito;
    }
    public Ejercicio getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }




}


