package com.alpirres.Modelo;
// Generated 03-dic-2019 8:56:38 by Hibernate Tools 4.3.1


import java.sql.Time;
import java.util.HashSet;
import java.util.Set;

/**
 * Ejercicio generated by hbm2java
 */
public class Ejercicio  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Time duracion;
     private int repeticiones;
     private int series;
     private Set circuEjercicios = new HashSet(0);
     private Set ejercicioMaterials = new HashSet(0);

    public Ejercicio() {
    }

	
    public Ejercicio(String nombre, Time duracion, int repeticiones, int series) {
        this.nombre = nombre;
        this.duracion = duracion;
        this.repeticiones = repeticiones;
        this.series = series;
    }
    public Ejercicio(String nombre, Time duracion, int repeticiones, int series, Set circuEjercicios, Set ejercicioMaterials) {
       this.nombre = nombre;
       this.duracion = duracion;
       this.repeticiones = repeticiones;
       this.series = series;
       this.circuEjercicios = circuEjercicios;
       this.ejercicioMaterials = ejercicioMaterials;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Time getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Time duracion) {
        this.duracion = duracion;
    }
    public int getRepeticiones() {
        return this.repeticiones;
    }
    
    public void setRepeticiones(int repeticiones) {
        this.repeticiones = repeticiones;
    }
    public int getSeries() {
        return this.series;
    }
    
    public void setSeries(int series) {
        this.series = series;
    }
    public Set getCircuEjercicios() {
        return this.circuEjercicios;
    }
    
    public void setCircuEjercicios(Set circuEjercicios) {
        this.circuEjercicios = circuEjercicios;
    }
    public Set getEjercicioMaterials() {
        return this.ejercicioMaterials;
    }
    
    public void setEjercicioMaterials(Set ejercicioMaterials) {
        this.ejercicioMaterials = ejercicioMaterials;
    }




}


