package com.alpirres.Modelo;
// Generated 03-dic-2019 8:56:38 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private Date alta;
     private int creditos;
     private int precio;

    public Factura() {
    }

    public Factura(Usuario usuario, Date alta, int creditos, int precio) {
       this.usuario = usuario;
       this.alta = alta;
       this.creditos = creditos;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    public Date getAlta() {
        return this.alta;
    }
    
    public void setAlta(Date alta) {
        this.alta = alta;
    }
    public int getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(int creditos) {
        this.creditos = creditos;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }




}


