package com.alpirres.Modelo;
// Generated 03-dic-2019 8:56:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int peso;
     private Set ejercicioMaterials = new HashSet(0);

    public Material() {
    }

	
    public Material(String nombre, int peso) {
        this.nombre = nombre;
        this.peso = peso;
    }
    public Material(String nombre, int peso, Set ejercicioMaterials) {
       this.nombre = nombre;
       this.peso = peso;
       this.ejercicioMaterials = ejercicioMaterials;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }
    public Set getEjercicioMaterials() {
        return this.ejercicioMaterials;
    }
    
    public void setEjercicioMaterials(Set ejercicioMaterials) {
        this.ejercicioMaterials = ejercicioMaterials;
    }




}


