package com.alpirres.Modelo;
// Generated 03-dic-2019 8:56:38 by Hibernate Tools 4.3.1


import java.sql.Time;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private Integer id;
     private Circuito circuito;
     private Timestamp fecha;
     private Time hora;
     private Set usuarioSesions = new HashSet(0);

    public Sesion() {
    }

	
    public Sesion(Circuito circuito, Timestamp fecha, Time hora) {
        this.circuito = circuito;
        this.fecha = fecha;
        this.hora = hora;
    }
    public Sesion(Circuito circuito, Timestamp fecha, Time hora, Set usuarioSesions) {
       this.circuito = circuito;
       this.fecha = fecha;
       this.hora = hora;
       this.usuarioSesions = usuarioSesions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Circuito getCircuito() {
        return this.circuito;
    }
    
    public void setCircuito(Circuito circuito) {
        this.circuito = circuito;
    }
    public Timestamp getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Timestamp fecha) {
        this.fecha = fecha;
    }
    public Time getHora() {
        return this.hora;
    }
    
    public void setHora(Time hora) {
        this.hora = hora;
    }
    public Set getUsuarioSesions() {
        return this.usuarioSesions;
    }
    
    public void setUsuarioSesions(Set usuarioSesions) {
        this.usuarioSesions = usuarioSesions;
    }




}


