package com.alpirres.Modelo;
// Generated 03-dic-2019 8:56:38 by Hibernate Tools 4.3.1



/**
 * UsuarioSesion generated by hbm2java
 */
public class UsuarioSesion  implements java.io.Serializable {


     private Integer id;
     private Sesion sesion;
     private Usuario usuario;

    public UsuarioSesion() {
    }

    public UsuarioSesion(Sesion sesion, Usuario usuario) {
       this.sesion = sesion;
       this.usuario = usuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sesion getSesion() {
        return this.sesion;
    }
    
    public void setSesion(Sesion sesion) {
        this.sesion = sesion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


